JobBatchName    = trigger_studies-label_training_data
Executable      = /cr/data01/filip/SdRecEvent/write_HE_library.sh

# error           = /cr/data01/filip/SdRecEvent/condor/errors-$(Process).err
# output          = /cr/data01/filip/SdRecEvent/condor/output-$(Process).log

request_memory  = 1G
max_idle        = 150

should_transfer_files = YES                                 
transfer_input_files  = /cr/data01/filip/SdRecEvent/AdstExtractor/AdstComponentExtractor
                                                                                                                
queue 1