# auto-generated by offline_installer.sh
# run this file with:
# source set_offline_env.sh
# to set your Offline environment

# Configuration for your Offline installation:
export AUGEROFFLINEROOT="/cr/data01/hahn/offline_versions/newest-stable/install"
eval $(bash $AUGEROFFLINEROOT/bin/this-auger-offline.sh)
# uncomment if you want to set env for all ape externals as well
# eval $($AUGEROFFLINEROOT/../ape/ape sh externals --rc=/cr/data01/hahn/offline_versions/newest-stable/aperc)
