JobBatchName    = production-test-nuria
Executable      = /cr/users/filip/Trigger/RunProductionTest/run_production_test.py

error           = /cr/users/filip/Trigger/RunProductionTest/output/errors-$(Process).err
# output          = /cr/users/filip/Trigger/RunProductionTest/output/output.out
# log             = /cr/users/filip/Trigger/RunProductionTest/output/logfle.log


arguments       = $(Process)
# arguments     = $(Item) $(Process1)
request_memory  = 2G
max_idle        = 150

# NURIA - 798
# LOQUI - 4000

queue 4000
# queue 2 in (0, 1, 2, 3, 4)
#       ^ step     ^ item  (or other way around?)