JobBatchName    = run-production-test-nuria-1vem
Executable      = /cr/users/filip/Trigger/RunProductionTest/run_production_test.py

error           = /cr/users/filip/Trigger/RunProductionTest/output/errors.err
# output          = /cr/users/filip/Trigger/RunProductionTest/output/output.out
# log             = /cr/users/filip/Trigger/RunProductionTest/output/logfle.log

arguments       = $(Process)   
request_memory  = 2G
max_idle        = 150

# NURIA - 798
# LOQUI - 801

queue 798
