JobBatchName    = eCNN_120_prior
Executable      = /cr/users/filip/EnsembleTrain/prior_estimation/prior.py

error           = /cr/users/filip/EnsembleTrain/output/prior-$(Process).err
output          = /cr/users/filip/EnsembleTrain/output/prior-$(Process).out
log             = /cr/users/filip/EnsembleTrain/output/prior-$(Process).log

arguments       = $(Process)
request_memory  = 5G
max_idle        = 150
max_retries     = 50
                                                            
should_transfer_files = YES                      

Requirements = (OpSysName == "Ubuntu" && OpSysMajorVer == 22) 
transfer_input_files  = /cr/work/filip/Binaries

queue 1