JobBatchName    = eCNN_120
Executable      = /cr/users/filip/EnsembleTrain/CNN_input_size/eCNN_120.py

error           = /cr/users/filip/EnsembleTrain/output/eCNN_120-$(Process).err
# output          = /cr/users/filip/EnsembleTrain/output/eCNN_120-$(Process).out
# log             = /cr/users/filip/EnsembleTrain/output/eCNN_120-$(Process).log

arguments       = $(Process)
request_memory  = 5G
max_idle        = 150
max_retries     = 50
                                                            
should_transfer_files = YES                      

Requirements = (OpSysName == "Ubuntu" && OpSysMajorVer == 22) 
transfer_input_files  = /cr/work/filip/Binaries

queue 10