JobBatchName   = trigger-studies_generate-trace-heatmap
Executable     = generate_trace_heatmap.py

error          = /cr/users/filip/condor_output/errors/trigger_studies-generate-$(ProcId).err
# output         = /cr/users/filip/condor_output/trigger_studies-$(ProcId).out
# log            = /cr/users/filip/condor_output/trigger_studies-$(ProcId).log

max_idle       = 149 
# solves max jobs per user problem

request_memory = 500M
arguments      = $(ProcId)

queue 203
