
JobBatchName   = trigger-studies_extract-vem-trace
Executable     = wrapper.sh

# error          = /cr/users/filip/condor_output/trigger_studies-$(ProcId).err
# output         = /cr/users/filip/condor_output/trigger_studies-$(ProcId).out
# log            = /cr/users/filip/condor_output/trigger_studies-$(ProcId).log

max_idle       = 150 
# solves max jobs per user problem

request_memory = 500M
arguments      = $(ProcId)

queue 20281

