JobBatchName    = trigger-studies_trace-heatmap
Executable      = generate_trace_heatmap.py

error           = /cr/users/filip/condor_output/errors/trigger-studies_studies_trace-heatmap.err
output          = /cr/users/filip/condor_output/output/trigger_studies_studies_trace-heatmap.out
log             = /cr/users/filip/condor_output/logs/trigger_studies_studies_trace-heatmap.log

max_idle        = 150
request_memory  = 1G

queue
