JobBatchName    = trigger-studies_second-model
Executable      = second_model_wrapper.sh

error           = /cr/users/filip/condor_output/errors/trigger-studies_second-model-1.err
output          = /cr/users/filip/condor_output/output/trigger-studies_second-model-1.out
log             = /cr/users/filip/condor_output/logs/trigger-studies_second-model-1.log

max_idle        = 150
request_memory  = 30G
Requirements = (TARGET.Machine == "crc2.ikp.kit.edu")

queue
