JobBatchName    = test_condor_issues
Executable      = /cr/users/filip/EnsembleTrain/testing_kill/test_job.py

error           = /cr/users/filip/EnsembleTrain/testing_kill/test.err
output          = /cr/users/filip/EnsembleTrain/testing_kill/test.out
log             = /cr/users/filip/EnsembleTrain/testing_kill/test.log

arguments       = $(Process)
request_memory  = 5G
max_idle        = 150
max_retries     = 50
                                                            
should_transfer_files = YES                      

Requirements = (OpSysName == "Ubuntu" && OpSysMajorVer == 22) 
transfer_input_files  = /cr/work/filip/Binaries

+Testing = true
queue 1