JobBatchName   = trigger-studies_create-NN-dataset
Executable     = create_data.py

error          = /cr/users/filip/condor_output/errors/trigger-studies-$(ProcId).err
# output         = /cr/users/filip/condor_output/output/trigger_studies-$(ProcId).out
# log            = /cr/users/filip/condor_output/logs/trigger_studies-$(ProcId).log

max_idle       = 149 
# solves max jobs per user problem

request_memory = 500M
arguments      = $(ProcId)

queue 100
