JobBatchName    = trigger-studies_first_model-train
Executable      = first_model_wrapper.sh

error           = /cr/users/filip/condor_output/errors/trigger-studies-first_model-train-network-150.err
output          = /cr/users/filip/condor_output/output/trigger_studies-first_model-train-network-150.out
log             = /cr/users/filip/condor_output/logs/trigger_studies-first_model-train-network-150.log

max_idle        = 150
request_memory  = 10G

Requirements = (TARGET.Machine == "crc2.ikp.kit.edu")

queue
